version: 2
updates:
  - package-ecosystem: "pip" 
    directory: "/"
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

    labels:
      - "dependencies"
      - "poetry"

    groups:
      prod-deps:
        dependency-type: "production"
        patterns:
          - "*"
      dev-deps:
        dependency-type: "development"
        patterns:
          - "*"
